apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
     deployment.kubernetes.io/revision: "2"
     kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"nginx","creationTimestamp":null},"spec":{"replicas":4,"template"}
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 5   
  template:
    metadata:
      labels:
        app: nginx
        service: http-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        
